spring:
  application:
    name: almina-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

  cors:
    allowed-origins: https://alminafrontend-invq.vercel.app

  security:
    debug-permit-all: false

  otp:
    expiry-minutes: 5
    sender-name: ALMINA
    from-email: ${APP_OTP_FROM_EMAIL}

  razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
